name: Create GitHub Repositories

on:
  workflow_dispatch:
    inputs:
      repo_names:
        description: 'Comma-separated list of repository names to create'
        required: true
        default: 'repo-1,repo-2,repo-3'
      github_token:
        description: 'GitHub personal access token'
        required: true
        secret: true

jobs:
  create-repos:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0  # Use the latest version of Terraform

      - name: Prepare Terraform Variables
        id: prepare_vars
        run: |
          # Split the comma-separated repo names into an array and format it for Terraform
          IFS=',' read -r -a repo_array <<< "${{ github.event.inputs.repo_names }}"
          formatted_repos=$(printf '%s\n' "${repo_array[@]}" | jq -R . | jq -s .)
          echo "REPO_NAMES=${formatted_repos}" >> $GITHUB_ENV
          echo "GITHUB_TOKEN=${{ github.event.inputs.github_token }}" >> $GITHUB_ENV

      - name: Configure Terraform
        run: |
          echo "github_token = \"${{ env.GITHUB_TOKEN }}\"" > terraform.tfvars
          echo "repo_names = ${REPO_NAMES}" >> terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
