name: Repository Creation Automation

on:
  repository_dispatch:
    types: [repository_creation]

jobs:
  create-repositories:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.0

      - name: Prepare Terraform Variables
        run: |
          echo "github_token = \"${{ secrets.MY_GITHUB_TOKEN }}\"" > terraform.tfvars
          echo "my_github_organization = \"${{ secrets.MY_GITHUB_ORGANIZATION }}\"" >> terraform.tfvars
          echo "emails = [\"$(echo ${{ github.event.client_payload.emails }} | tr ',' '\",\"')\"]" >> terraform.tfvars

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
