name: Generate and Send CSV

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual triggering of the workflow

jobs:
  generate_and_send_csv:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            python -m pip install -r requirements.txt
          else
            echo "No requirements.txt found, skipping dependency installation"
          fi

      - name: Generate CSV file
        run: |
          python Generate.py
        # Make sure gen.py generates 'output.csv' or the file name you expect

      - name: Upload CSV file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: csv-file
          path: output.csv
        # Adjust the path to match the generated CSV file's location and name

      # Optional: Notify or take action after uploading
      # - name: Send Notification
      #   run: |
      #     # Add your notification or follow-up commands here